Feature/navigation
feivlinus/fork-yeah pull request #22
Opened 2023-11-29 15:36 UTC by vlatkojuric

Added a Navigation that can lead to create new recipes form and a home button which when clicked leads to the home page where the list of recipes is. For now, only on the mobile view when clicked the icon changes a color but later in our Styling user story we will make it also do the same on web.

2023-11-30 13:47 UTC, onemanwenttomow requested changes
Nice effort team. 🎉 Added a couple of small suggestions.

2023-11-30 13:47 UTC, onemanwenttomow commented on components/Navigation.js
> +  height: 3.5rem;
It might be safer to use padding to add the vertical spacing. That way if your icons were to get larger in the future the height of the container will grow accordingly.

2023-11-30 13:47 UTC, onemanwenttomow commented on components/Navigation.js
> +const StyledNavigationContainer = styled.div`
We might want to consider a `footer` html element here.

We could then nest a `nav` html element inside. 

And then i would consider wrapping your links in a `ul`. 

i.e. following this structure. 

``` html
<footer>
  <nav>
    <ul>
      <li><a href="#home">Home</a></li>
      <li><a href="#about">About</a></li>
      <li><a href="#contact">Contact</a></li>
    </ul>
  </nav>
</footer>
```

2023-12-01 10:33 UTC, Shahab-Ziaeian commented
Hey @onemanwenttomow thanks a lot for the tips! We made the changes you suggested.

2023-12-01 11:17 UTC, lennart-kaminsky approved these changes
Hey Team Fork Yeah!

LGTM! 🙌  🍕 

Just a tiny, tiny, tiny suggestion:
For some potential future styling of your navigation bar you could consider giving your icons a special color or any styling that shows the user on which page they are on.

2023-12-01 11:17 UTC, lennart-kaminsky commented on components/Navigation.js
> +      </Link> */}
👀

2023-12-01 13:52 UTC, feivlinus commented
> Hey Team Fork Yeah!
> 
> LGTM! 🙌 🍕
> 
> Just a tiny, tiny, tiny suggestion: For some potential future styling of your navigation bar you could consider giving your icons a special color or any styling that shows the user on which page they are on.

Thank you @lennart-kaminsky for your review. Good that you mention that. We have that in mind. We have a special effect for the icons we havent implemented yet. There will be svg filters applied inside the svgs which would switch by calling them with css. We planed to implement that at user story - style. We havent forgot your suggestion :) from before.

2023-12-01 14:02 UTC, Shahab-Ziaeian approved these changes
tiptop

2023-12-01 14:03 UTC, merged