Feature/favorites page
feivlinus/fork-yeah pull request #24
Opened 2023-12-01 14:13 UTC by feivlinus

https://github.com/feivlinus/fork-yeah/issues/12

2023-12-01 15:33 UTC, Roland-Hufnagel requested changes
Hey Team Fork Yeah. Good work 💪. Just a few small improvements, I want you to look at.

2023-12-01 15:33 UTC, Roland-Hufnagel commented on components/Navigation.js
> +              <NavigationIcons
Since this is only ONE icon I would recommend to name it ``NavigationIcon``.

2023-12-01 15:33 UTC, Roland-Hufnagel commented on components/Navigation.js
> +                size={32}
And because all your icons have the same color and the same size you could define this color and size as a default in the NavigationIcon Component. Then you don't need to define these props every time.

2023-12-01 15:33 UTC, Roland-Hufnagel commented on pages/favorites.js
> +export default function favoritesPage({
```suggestion
export default function FavoritesPage({
```

2023-12-01 15:33 UTC, Roland-Hufnagel commented on pages/favorites.js
> +        </StyledNoteContainer>
Do you really need a ``p`` in a ``flexbox`` in a ``flexbox`` ?

2023-12-04 10:09 UTC, feivlinus commented
> Hey Team Fork Yeah. Good work 💪. Just a few small improvements, I want you to look at.

Thank you Roland for your time and suggestions! We applied all suggestion you mentioned.

2023-12-04 14:05 UTC, Roland-Hufnagel approved these changes
Great 🏄👍

2023-12-04 18:24 UTC, merged